package com.him.landlordtenant.app.enums

/**
 * =============================================================
 * NOTIFICATION TYPE
 * =============================================================
 *
 * Central list of notification events generated by the system.
 *
 * Notifications may be triggered by:
 * - Tenant actions
 * - Landlord actions
 * - Caretaker actions
 * - Broker actions
 * - Professional actions
 * - Payments
 * - Agreements
 * - Maintenance
 * - Property events
 * - Verification
 * - Automated system rules
 *
 * =============================================================
 */

enum class NotificationType(
    val displayName: String,
    val description: String,
    val category: NotificationCategory,
    val defaultPriority: NotificationPriority,
    val requiresAction: Boolean
) {

    /*
     * ---------------------------------------------------------
     * FINANCE / RENT
     * ---------------------------------------------------------
     */

    RENT_DUE(
        "Rent Due",
        "Tenant's rent is due.",
        NotificationCategory.FINANCE,
        NotificationPriority.HIGH,
        true
    ),

    RENT_DUE_SOON(
        "Rent Due Soon",
        "Tenant's rent due date is approaching.",
        NotificationCategory.FINANCE,
        NotificationPriority.NORMAL,
        true
    ),

    RENT_OVERDUE(
        "Rent Overdue",
        "Tenant has an outstanding overdue rent balance.",
        NotificationCategory.FINANCE,
        NotificationPriority.CRITICAL,
        true
    ),

    BILL_CREATED(
        "New Bill",
        "A new bill has been issued.",
        NotificationCategory.FINANCE,
        NotificationPriority.NORMAL,
        true
    ),

    BILL_DUE_SOON(
        "Bill Due Soon",
        "A property bill is approaching its due date.",
        NotificationCategory.FINANCE,
        NotificationPriority.NORMAL,
        true
    ),

    BILL_OVERDUE(
        "Bill Overdue",
        "A property bill has become overdue.",
        NotificationCategory.FINANCE,
        NotificationPriority.HIGH,
        true
    ),

    PAYMENT_INITIATED(
        "Payment Initiated",
        "A payment has been initiated.",
        NotificationCategory.FINANCE,
        NotificationPriority.NORMAL,
        false
    ),

    PAYMENT_SUCCESS(
        "Payment Successful",
        "Payment was successfully completed.",
        NotificationCategory.FINANCE,
        NotificationPriority.NORMAL,
        false
    ),

    PAYMENT_FAILED(
        "Payment Failed",
        "A payment failed.",
        NotificationCategory.FINANCE,
        NotificationPriority.HIGH,
        true
    ),

    PAYMENT_REVERSED(
        "Payment Reversed",
        "A previously completed payment was reversed.",
        NotificationCategory.FINANCE,
        NotificationPriority.CRITICAL,
        true
    ),

    PAYMENT_REFUNDED(
        "Payment Refunded",
        "A payment has been refunded.",
        NotificationCategory.FINANCE,
        NotificationPriority.NORMAL,
        false
    ),

    PAYMENT_RECEIPT(
        "Payment Receipt",
        "A payment receipt is available.",
        NotificationCategory.FINANCE,
        NotificationPriority.LOW,
        false
    ),

    /*
     * ---------------------------------------------------------
     * AGREEMENTS
     * ---------------------------------------------------------
     */

    AGREEMENT_CREATED(
        "Agreement Created",
        "A new tenancy agreement has been created.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.NORMAL,
        false
    ),

    AGREEMENT_SIGN_REQUEST(
        "Signature Required",
        "A tenancy agreement requires your signature.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.HIGH,
        true
    ),

    AGREEMENT_SIGNED(
        "Agreement Signed",
        "A tenancy agreement has been signed.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.NORMAL,
        false
    ),

    AGREEMENT_REJECTED(
        "Agreement Rejected",
        "A tenancy agreement has been rejected.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.HIGH,
        true
    ),

    AGREEMENT_APPROVED(
        "Agreement Approved",
        "A tenancy agreement has been approved.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.NORMAL,
        false
    ),

    AGREEMENT_EXPIRING(
        "Agreement Expiring",
        "A tenancy agreement is approaching its expiry date.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.HIGH,
        true
    ),

    AGREEMENT_EXPIRED(
        "Agreement Expired",
        "A tenancy agreement has expired.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.HIGH,
        true
    ),

    AGREEMENT_RENEWAL_REQUEST(
        "Renewal Requested",
        "A tenancy agreement renewal requires attention.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.HIGH,
        true
    ),

    AGREEMENT_TERMINATED(
        "Agreement Terminated",
        "A tenancy agreement has been terminated.",
        NotificationCategory.AGREEMENT,
        NotificationPriority.HIGH,
        true
    ),

    /*
     * ---------------------------------------------------------
     * MAINTENANCE
     * ---------------------------------------------------------
     */

    MAINTENANCE_CREATED(
        "Maintenance Request",
        "A new maintenance request has been created.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.NORMAL,
        true
    ),

    MAINTENANCE_ASSIGNED(
        "Maintenance Assigned",
        "A maintenance request has been assigned to you.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.HIGH,
        true
    ),

    MAINTENANCE_ACCEPTED(
        "Maintenance Accepted",
        "A professional accepted a maintenance request.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.NORMAL,
        false
    ),

    MAINTENANCE_SCHEDULED(
        "Maintenance Scheduled",
        "Maintenance work has been scheduled.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.NORMAL,
        false
    ),

    MAINTENANCE_STARTED(
        "Maintenance Started",
        "Maintenance work has started.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.NORMAL,
        false
    ),

    MAINTENANCE_COMPLETED(
        "Maintenance Completed",
        "Maintenance work has been marked as completed.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.NORMAL,
        true
    ),

    MAINTENANCE_CONFIRMATION_REQUIRED(
        "Confirm Maintenance",
        "Tenant confirmation is required.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.HIGH,
        true
    ),

    MAINTENANCE_DISPUTED(
        "Maintenance Disputed",
        "Completed maintenance work has been disputed.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.HIGH,
        true
    ),

    MAINTENANCE_CANCELLED(
        "Maintenance Cancelled",
        "A maintenance request has been cancelled.",
        NotificationCategory.MAINTENANCE,
        NotificationPriority.NORMAL,
        false
    ),

    MAINTENANCE_EMERGENCY(
        "Emergency Maintenance",
        "An emergency maintenance request requires immediate attention.",
        NotificationCategory.EMERGENCY,
        NotificationPriority.CRITICAL,
        true
    ),

    /*
     * ---------------------------------------------------------
     * MESSAGING
     * ---------------------------------------------------------
     */

    NEW_MESSAGE(
        "New Message",
        "You have received a new message.",
        NotificationCategory.MESSAGING,
        NotificationPriority.NORMAL,
        false
    ),

    MESSAGE_MENTION(
        "Mention",
        "You were mentioned in a conversation.",
        NotificationCategory.MESSAGING,
        NotificationPriority.NORMAL,
        false
    ),

    CONVERSATION_INVITE(
        "Conversation Invitation",
        "You have been invited to a conversation.",
        NotificationCategory.MESSAGING,
        NotificationPriority.NORMAL,
        true
    ),

    /*
     * ---------------------------------------------------------
     * PROPERTY / VIEWINGS
     * ---------------------------------------------------------
     */

    PROPERTY_AVAILABLE(
        "Property Available",
        "A property has become available.",
        NotificationCategory.PROPERTY,
        NotificationPriority.NORMAL,
        false
    ),

    PROPERTY_RESERVED(
        "Property Reserved",
        "A property has been reserved.",
        NotificationCategory.PROPERTY,
        NotificationPriority.NORMAL,
        false
    ),

    PROPERTY_VERIFIED(
        "Property Verified",
        "A property has been successfully verified.",
        NotificationCategory.PROPERTY,
        NotificationPriority.NORMAL,
        false
    ),

    VIEWING_REQUEST(
        "Viewing Request",
        "A prospective tenant requested a property viewing.",
        NotificationCategory.PROPERTY,
        NotificationPriority.HIGH,
        true
    ),

    VIEWING_CONFIRMED(
        "Viewing Confirmed",
        "A property viewing has been confirmed.",
        NotificationCategory.PROPERTY,
        NotificationPriority.NORMAL,
        false
    ),

    VIEWING_REMINDER(
        "Viewing Reminder",
        "A scheduled property viewing is approaching.",
        NotificationCategory.PROPERTY,
        NotificationPriority.HIGH,
        false
    ),

    VIEWING_CANCELLED(
        "Viewing Cancelled",
        "A property viewing has been cancelled.",
        NotificationCategory.PROPERTY,
        NotificationPriority.NORMAL,
        false
    ),

    /*
     * ---------------------------------------------------------
     * PROFESSIONALS
     * ---------------------------------------------------------
     */

    PROFESSIONAL_JOB_OFFER(
        "New Job",
        "A professional has received a new job offer.",
        NotificationCategory.PROFESSIONAL,
        NotificationPriority.HIGH,
        true
    ),

    PROFESSIONAL_JOB_ACCEPTED(
        "Job Accepted",
        "A professional accepted a job.",
        NotificationCategory.PROFESSIONAL,
        NotificationPriority.NORMAL,
        false
    ),

    PROFESSIONAL_JOB_REJECTED(
        "Job Rejected",
        "A professional rejected a job.",
        NotificationCategory.PROFESSIONAL,
        NotificationPriority.NORMAL,
        true
    ),

    PROFESSIONAL_VERIFIED(
        "Professional Verified",
        "Professional verification has been completed.",
        NotificationCategory.VERIFICATION,
        NotificationPriority.NORMAL,
        false
    ),

    PROFESSIONAL_CERTIFICATION_EXPIRING(
        "Certification Expiring",
        "A professional certification is approaching expiry.",
        NotificationCategory.VERIFICATION,
        NotificationPriority.HIGH,
        true
    ),

    PROFESSIONAL_CERTIFICATION_EXPIRED(
        "Certification Expired",
        "A required professional certification has expired.",
        NotificationCategory.VERIFICATION,
        NotificationPriority.CRITICAL,
        true
    ),

    /*
     * ---------------------------------------------------------
     * IDENTITY / VERIFICATION
     * ---------------------------------------------------------
     */

    IDENTITY_VERIFICATION_REQUIRED(
        "Identity Verification Required",
        "Identity verification is required.",
        NotificationCategory.VERIFICATION,
        NotificationPriority.HIGH,
        true
    ),

    IDENTITY_VERIFIED(
        "Identity Verified",
        "Identity verification was successful.",
        NotificationCategory.VERIFICATION,
        NotificationPriority.NORMAL,
        false
    ),

    IDENTITY_VERIFICATION_FAILED(
        "Verification Failed",
        "Identity verification was unsuccessful.",
        NotificationCategory.VERIFICATION,
        NotificationPriority.HIGH,
        true
    ),

    /*
     * ---------------------------------------------------------
     * SECURITY / EMERGENCY
     * ---------------------------------------------------------
     */

    SECURITY_ALERT(
        "Security Alert",
        "A security-related event requires attention.",
        NotificationCategory.SECURITY,
        NotificationPriority.CRITICAL,
        true
    ),

    EMERGENCY_ALERT(
        "Emergency Alert",
        "An emergency event requires immediate attention.",
        NotificationCategory.EMERGENCY,
        NotificationPriority.CRITICAL,
        true
    ),

    /*
     * ---------------------------------------------------------
     * SYSTEM
     * ---------------------------------------------------------
     */

    SYSTEM_ANNOUNCEMENT(
        "System Announcement",
        "Important information from the platform.",
        NotificationCategory.SYSTEM,
        NotificationPriority.NORMAL,
        false
    ),

    ACCOUNT_WARNING(
        "Account Warning",
        "Your account requires attention.",
        NotificationCategory.SYSTEM,
        NotificationPriority.HIGH,
        true
    ),

    ACCOUNT_SUSPENDED(
        "Account Suspended",
        "Your account has been suspended.",
        NotificationCategory.SECURITY,
        NotificationPriority.CRITICAL,
        true
    );

    /*
     * ---------------------------------------------------------
     * HELPERS
     * ---------------------------------------------------------
     */

    val isUrgent: Boolean
        get() =
            defaultPriority == NotificationPriority.CRITICAL

    val isFinancial: Boolean
        get() =
            category == NotificationCategory.FINANCE

    val isMaintenance: Boolean
        get() =
            category == NotificationCategory.MAINTENANCE ||
                    category == NotificationCategory.EMERGENCY

    val isAgreement: Boolean
        get() =
            category == NotificationCategory.AGREEMENT

    val isMessage: Boolean
        get() =
            category == NotificationCategory.MESSAGING

    val isPropertyRelated: Boolean
        get() =
            category == NotificationCategory.PROPERTY

    val isVerificationRelated: Boolean
        get() =
            category == NotificationCategory.VERIFICATION

    val isSecurityRelated: Boolean
        get() =
            category == NotificationCategory.SECURITY ||
                    category == NotificationCategory.EMERGENCY

    companion object {

        fun fromValue(value: String?): NotificationType? {
            if (value.isNullOrBlank()) return null

            return entries.firstOrNull {
                it.name.equals(value, ignoreCase = true) ||
                        it.displayName.equals(value, ignoreCase = true)
            }
        }

        fun fromValueOrDefault(
            value: String?,
            default: NotificationType = SYSTEM_ANNOUNCEMENT
        ): NotificationType {
            return fromValue(value) ?: default
        }
    }
}
